# vars file for ans_zeronetworks_misc_role
ssh_key_path:  "{{ lookup('community.hashi_vault.vault_kv2_get', 'breakglass/group1/sshkey', engine_mount_point='secret') }}"
win_username:  "{{ lookup('community.hashi_vault.vault_kv2_get', 'breakglass/group1/winuser', engine_mount_point='secret') }}"
win_userpass:  "{{ lookup('community.hashi_vault.vault_kv2_get', 'breakglass/group1/winpasswd', engine_mount_point='secret') }}"
segmentServers:
 - segSrv01
 - segSrv02
 - segSrv03
 - segSrv04
 - segSrv05